### ISSUE TITLE
Can't use < when column is in on the right side of expression

### ISSUE THREAD

**Issue by aquach** [Clinkle/stilts#2]
```
com.clinkle.managers.OnboardingDBM.DB.onboarding_mail.Column[com.clinkle.application.types.primitives.Time]#NOT_NULL.type
 required: com.clinkle.application.types.primitives.Time
      .WHERE(time_sent.IS_NULL AND AppTime.currentTime > time_scheduled).exec.toList
```

Switching to `time_scheduled < AppTime.currentTime` doesn't work.

**Comment by wmrowan** [comment]
I assume you mean "switching to `time_scheduled < AppTime.currentTime` *does* work".

For `AppTime.currentTime < time_sceduled` to work, Scala would have to apply two successive implicits to the expression `AppTime.currentTime`, effectively wrapping it like this:

```
ComparableExpr(Arg(AppTime.currentTime)) < time_scheduled
```

Scala will not successively apply two implicit conversions to the same value when trying to solve a type equation. Allowing for deeply nested implicit applications quickly leads to an exponential explosion of possible solutions so the Scala designers decided simply to stop at one level.

The alternative of `time_scheduled < AppTime.currentTime` still has two implicit applications but they are not nested. Scala will happily apply a single implicit conversion each to any number of arguments to solve the type equation:

```
ComparableExpr(time_scheduled) < Arg(AppTime.currentTime)
```

Scala never makes a guarantee that it will find a correct solution through implicit application even if one is theoretically available. The compiler is conservative when finding solutions. You can always manually apply the implicits you expect in this case. The easiest thing to do in this case would be to manually apply `Arg` to simplify the type equation sufficiently for Scala to solve the rest on its own.

```
Arg(AppTime.currentTime) < time_scheduled
```

One thing we could do to prevent the need for successive implicits would be to mix `ComparableExpr` and similar implicit classes directly into `Expr`. This is not a general solution, however, since it only works for the implicit classes like `ComparableExpr` and `NullableExpr` that apply to all valid `Expr`s. Some implicit classes like `NumericExpr` can't be mixed it into the `Expr` base class because those methods are only valid for `Expr`s of some numeric type. Thus you would still run into the successive implicits problem for expressions like:

```
AppTime.currentTime - time_scheduled
```

There might be a way to apply this solution generally with a "normal" type hierarchy but that would require rethinking the whole `Expr` and `Primitive` class interaction and probably would entail losing some of the flexibility we now enjoy with the current implicits based design.

I'm just going to leave it as it is for now and will make a note of implicit nesting when I eventually get to the documentation.
